### ISSUE TITLE
Force text to one line

### ISSUE THREAD

**Issue by elmerland** [davatron5000/FitText.js#111]
Hi, just started using FitText. I'm trying to make my title responsive and at the same time make it occupy only one line of text at all times. I can't seem to figure out why FitText splits my header into two lines. Below is a sample of my code. I don't know if this a feature of the plugin or if I'm supposed to explicitly tell the title to be in one line.

HTML:

```
<header>
  <h1 id="my-title">My Somewhat Long Title</h1>
</header>
```

JS:

```
$(document).ready(function() {
  $("#my-title").fittext();
});
```

**Comment by vlrprbttst** [comment]
i'm having the same "problem"..

> Oh, and don't you dare let us catch you using FitText on paragraph text. This is for gigantic display text only!

but still, that would a good feature.

**Comment by breadadams** [comment]
Yeah it'd be **very** handy. For example, in the case of a dynamic label (entered by a user) that could be any number of characters.

Great plugin nonetheless 😄

**Comment by davatron5000** [comment]
I recommend checking out [BigText](https://www.zachleat.com/web/bigtext-makes-text-big/) or [Fitter Happier Text](http://jxnblk.com/fitter-happier-text/) for single line text.
