### ISSUE TITLE
Doesn't work proper with one word only?

### ISSUE THREAD

**Issue by marcelhadorn** [davatron5000/FitText.js#116]
To me it seems like it downsizes titles too much, especially on short words, see this example:
http://duotones.ch/article/spring.html

While it works perfectly on this example:
http://duotones.ch/article/naturkostbar.html

Settings are the following:

```

jQuery(".fittext").fitText(0.87, { minFontSize: '30px', maxFontSize: '119px' });
```

or am I missing something?

**Comment by aabdolla** [comment]
@Marc3llo Did you ever find a solution for the one word problem?

**Comment by marcelhadorn** [comment]
@aabdolla I honestly can't remember if I did or just headed for a different solution, sorry.
