### ISSUE TITLE
Add refresh function to callback !

### ISSUE THREAD

**Issue by jimmyphong** [davatron5000/FitText.js#130]
need add refresh or callback function to this plugin !
ready thank !

**Comment by jimmyphong** [comment]
Also this does not work with hidden element like bootstrap carousel !
any guy make this work with bootstrap carousel ?

**Comment by davatron5000** [comment]
Closed due to no reduced testcase.

Probable solution, apply FitText before applying the carousel.

**Comment by jimmyphong** [comment]
Hi davatron5000
here is JSFiddle link for testest with fittext and bootstrap carousel 

https://jsfiddle.net/jimmyphong/867wvc9u/2/

You can see fittext only work fine with first and active item , with another carousel item , it's not working

Thanks !
