### ISSUE TITLE
Can I convert plugin for Joomla?

### ISSUE THREAD

**Issue by vitorvmax** [davatron5000/FitText.js#132]
Hello, I wonder if I can convert your plugin for Joomla, joomla leave the name as JP_FitText, let my credits and yours.
  Then send in the Joomla Extensions repository?
extensions.joomla.org

  Thank U

**Comment by davatron5000** [comment]
Definitely. This is [WTFPL](http://www.wtfpl.net/) and I have no plans on creating a Joomla plugin. Hope it goes great.
