### ISSUE TITLE
problem - long word - germany

### ISSUE THREAD

**Issue by cyberkatze** [davatron5000/FitText.js#133]
Hi,

we have problem with long words (Germany language). 
For example: "Unternehmenslösungen"
max font-size: 80px. if we use bootstrap2.x with
<div class="container"><div class="row"><div class="span12">text</div></div></div>
text will be going outer of content-block and will be not scale up to block width.
if string have blank-chars all work fine!

**Comment by TrentWalton** [comment]
Do you have an isolated use case on something like codepen.io we could look at?

Also, read: https://github.com/davatron5000/FitText.js/blob/master/README.md

You might need to adjust the Compressor
```
The Compressor

If your text is resizing poorly, you'll want to turn tweak up/down "The Compressor". It works a little like a guitar amp. The default is 1.

jQuery("#responsive_headline").fitText(1.2); // Turn the compressor up   (resizes more aggressively)
jQuery("#responsive_headline").fitText(0.8); // Turn the compressor down (resizes less aggressively)
This will hopefully give you a level of "control" that might not be pixel perfect, but resizes smoothly & nicely.
```

**Comment by davatron5000** [comment]
Closing due to no reduced test case.
