### ISSUE TITLE
No destroy method == memory leak

### ISSUE THREAD

**Issue by JSteunou** [davatron5000/FitText.js#135]
there is a window.on but no off

you should expose a destroy method that unbind event listener.

**Comment by davatron5000** [comment]
Closed due to no reduced test case.

http://api.jquery.com/off/

**Comment by JSteunou** [comment]
so this plugin does a .on but it's on user to call .off ?

**Comment by davatron5000** [comment]
Yeah, if it's something you need to turn off you can totally make that happen.

**Comment by JSteunou** [comment]
So I would write several `off` in my code, but if someday you change your events or add some, I would rewrite my code.

Good practice is to expose a destroy method.

**Comment by Petah** [comment]
+1 on a single page app with many elements being created and destroyed this does leak memory, and reduce performance.

**Comment by Petah** [comment]
Also we can't manually call off because the event function is not exposed to the app scope.

**Comment by FezVrasta** [comment]
+1

**Comment by JSteunou** [comment]
@FezVrasta fork it @davatron5000 is not open to it and not maintaining it anymore...

**Comment by davatron5000** [comment]
I'm not opposed. Just busy. Will try to look at it today after a few @a11yproject things. 





On Tue, Jan 5, 2016 at 6:47 AM -0800, "Jérôme Steunou" <notifications@github.com> wrote:












@FezVrasta fork it @davatron5000 is not open to it and not maintaining it anymore...

**Comment by FezVrasta** [comment]
@JSteunou I've already did it, unfortunately I need some more advanced feature. 

@davatron5000 thanks for the effort

**Comment by Petah** [comment]
Not sure why the issue is closed though, as it clearly is an issue.

**Comment by davatron5000** [comment]
@Petah It was closed due no reduced test case per the `contributing.md`. I'll take a look at #136 but I can't just merge to master something that says "Should fix some issue" without vetting it first. No reduced test case means I have to take more of my time to get that integrated.

> Also we can't manually call off because the event function is not exposed to the app scope.

I don't have a single line of code from you explaining what you're trying to do. I can't tell if this is super unique to your implementation or not. I don't know if you've rolled out @JSteunou's fork and if that has worked for you. I literally don't know anything at this point other than a few +1's.

If I could get concrete feedback from anyone on this thread as opposed to pejorative quips, that would be much appreciated and I'll consider reopening.

**Comment by FezVrasta** [comment]
Ok, you bind an event with

```js
$(window).on('resize', myFn);
```

you instead have to:

```js
var myFnBound = myFn.bind(arg1, arg2, arg3);
$(window).on('resize', myFnBound);
```

and in the `destroy` method:

```js
$(window).off('resize', myFnBound);
```

**Comment by Petah** [comment]
I don't think its really possible to create a test case for not being able to unbind an event.
