### ISSUE TITLE
Why this plugin?

### ISSUE THREAD

**Issue by dr-dimitru** [davatron5000/FitText.js#148]
Hi @davatron5000 ,
Why use this plugin when we can set font size relative to viewport (in `vw` or `vh`) or container (in `%`)?
I'll be appreciated for explanation of differences.

**Comment by charlespeters** [comment]
this jquery plugin predates decent browser support for vw and vh units. there are other methods of doing this namely [FITTER HAPPIER TEXT](http://jxnblk.com/fitter-happier-text/). this plugin also maintains the headline across a line without wrapping.
