### ISSUE TITLE
"the compressor" exhibits inverse behavior

### ISSUE THREAD

**Issue by savraj** [davatron5000/FitText.js#152]
Compressor value < 1, I get insanely huge text, compressor value > 1, I get more reasonably resized text.  The docs imply the opposite behavior. :)

**Comment by davatron5000** [comment]
Sorry it's confusing, but it's been like this for over 5 years now so any changes would be a breaking change. It's a compressor, so large numbers compress more. Hope that helps.

**Comment by savraj** [comment]
My request is simply to make this behavior more clear in the documentation, no code change required.  It's a great little script, thanks for it.
