### ISSUE TITLE
Have support with bootstrap

### ISSUE THREAD

**Issue by Root3287** [davatron5000/FitText.js#156]
As the name implies

**Comment by charlespeters** [comment]
@Root3287 is there a portion of fittext that you've found is incompatiable with bootstrap? are you getting any errors in your console, etc? could you provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)?

**Comment by Root3287** [comment]
I am not sure, I imported the file into one my projects because someone posted: "NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOB" and the script didn't really worked at fitting the text... I later used css to fix the problem...

But i totally forgot the problem was... sorry...

**Comment by charlespeters** [comment]
okay well dropping a dependencies is always a good thing! closing this issue, open another if you have anymore questions
