### ISSUE TITLE
Strange works with multiple spans inside a div

### ISSUE THREAD

**Issue by xahon** [davatron5000/FitText.js#158]
Hello. My div has both width and height and displays as block but text won't fit parent

Structure as at the screen

![issue](https://cloud.githubusercontent.com/assets/18731681/18807468/4abf8e80-828b-11e6-8104-94dee672eb1f.png)

**Comment by davatron5000** [comment]
Sorry. Can't help without a [reduced test case](https://css-tricks.com/reduced-test-cases/). Please put this in something editable/forkable like a CodePen.
