### ISSUE TITLE
Text doesn't resize to fit div

### ISSUE THREAD

**Issue by Rvervuurt** [davatron5000/FitText.js#163]
I'm trying to use this plugin, but I'm running into the following problem:

The text is resized (or: it is a different size than it should, because of the plugin), but it's not made so big that it fills the whole div. See [this fiddle](https://jsfiddle.net/tezq9rwn/)

Or, if the text is very long (as in my [example fiddle](https://jsfiddle.net/tezq9rwn/4/)), it doesn't become a very small font, to fit in the div.

Am I doing something wrong? Since I don't know what text will be resized (the customer will change it to whatever they want, probably with a max-character-count on it though), I can't play around with the compressor.

**Comment by davatron5000** [comment]
This is all in the Readme, but FitText does ratio-based resizing based on the Parent's width. If you want exact fitting text I recommend [BigText](https://www.zachleat.com/web/bigtext-makes-text-big/) or the SVG-based [Fitter Happier Text](http://jxnblk.com/fitter-happier-text/)
