### ISSUE TITLE
What's the difference between fittext.js and using vw for font sizes?

### ISSUE THREAD

**Issue by birdbrainsolutions** [davatron5000/FitText.js#171]
What the title said, and thank you for creating the plugin

**Comment by TrentWalton** [comment]
Hi! I'd probably use viewport units at this point—this plugin was created before VW units were widely used / supported.

**Comment by neueweide** [comment]
Hey i just had the same thought... a javascript with 43 lines of code (including the empty lines) is contributed by 15 Contributors... so every Contributor has typed one line or what? 
This is a joke sorry ;)

This guy David Rupert seems to be a blender... for a developer he talks much and codes less ;)

I'm really amazed how such a stupid script has this popularity?
The core line of your script is a simple math calculation: Container Width / 10
Why 10?
Is there something deeper in thought why you are deviding the container width through a fixed number?

the oddest thing i saw until now...
