### ISSUE TITLE
Specify a 100% value for a text, then reduce it-25% for a given screen size media query

### ISSUE THREAD

**Issue by tomasts248** [davatron5000/FitText.js#173]
```
Say I have a 
h1 {font-size: 40px;}
p {font-size: 18px;}

@media (max-width: 500px) {
	h1, p {
		font-size:75%;
	}
}
```
Ok so for performance reasons this is not feasible with FitText, but is it doable in the form of a jquery plugin or definitively is a no-no?

**Comment by davatron5000** [comment]
Hi. We don't help with specific support questions here. This is for BUGS 🐛  that occur with the jQuery plugin. 

You could maybe use regular CSS for this using `em` units.
