### ISSUE TITLE
Icon font issue

### ISSUE THREAD

**Issue by imrefazekas** [davatron5000/FitText.js#75]
Hello,

I'm using icon fonts and I add them to my page via span but fittext does not do anything with it unfortunately.

Had anyone success with span icon fonts?

**Comment by jtara** [comment]
I was going to make a new Issue for this, but it is just a hint and not really an Issue. Hopefully people will find it here...

I wanted to size a spinner to the width of the screen. (Using font-awesome). Yea, the "right" approach is to use an SVG. Or, in newer browsers (too few of them...) *vw* CSS units. (But unfortunately, Android only supports from 4.4).

I already had the `<i>` tag as *display:block*.

Took a bit of fiddling to figure out what the "compressor" values mean. This worked for me:

`$('.login-spinner-symbol').fittext(0.1);`

Thanks!
